version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: containername
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: username
      MYSQL_DATABASE: database
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p0000"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
